name: "Penghijauan"
author: "lendradx"
description: "Membantu menghijaukan akun github anda yang sangat tandus"

inputs:
  GITHUB_TOKEN:
    description: "Github token dengan mencakup ijin untuk mengakses repository"
    required: true
    default: ${{ github.token }}
  REPOSITORY:
    description: "Repository githubmu"
    required: false
    default: ${{ github.repository }}
  BRANCH:
    description: "Branch yang mau dimonitoring"
    required: false
    default: "master"
  EMAIL:
    description: "Alamat email milikmu"
    required: true
  USERNAME:
    description: "Username mu"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"